// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: .proto/client/client.proto

package client

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FileSaving_RequestNodeIPs_FullMethodName = "/client.FileSaving/RequestNodeIPs"
)

// FileSavingClient is the client API for FileSaving service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileSavingClient interface {
	RequestNodeIPs(ctx context.Context, in *RequestNodeIPsRequest, opts ...grpc.CallOption) (*RequestNodeIPsResponse, error)
}

type fileSavingClient struct {
	cc grpc.ClientConnInterface
}

func NewFileSavingClient(cc grpc.ClientConnInterface) FileSavingClient {
	return &fileSavingClient{cc}
}

func (c *fileSavingClient) RequestNodeIPs(ctx context.Context, in *RequestNodeIPsRequest, opts ...grpc.CallOption) (*RequestNodeIPsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestNodeIPsResponse)
	err := c.cc.Invoke(ctx, FileSaving_RequestNodeIPs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileSavingServer is the server API for FileSaving service.
// All implementations must embed UnimplementedFileSavingServer
// for forward compatibility.
type FileSavingServer interface {
	RequestNodeIPs(context.Context, *RequestNodeIPsRequest) (*RequestNodeIPsResponse, error)
	mustEmbedUnimplementedFileSavingServer()
}

// UnimplementedFileSavingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileSavingServer struct{}

func (UnimplementedFileSavingServer) RequestNodeIPs(context.Context, *RequestNodeIPsRequest) (*RequestNodeIPsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestNodeIPs not implemented")
}
func (UnimplementedFileSavingServer) mustEmbedUnimplementedFileSavingServer() {}
func (UnimplementedFileSavingServer) testEmbeddedByValue()                    {}

// UnsafeFileSavingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileSavingServer will
// result in compilation errors.
type UnsafeFileSavingServer interface {
	mustEmbedUnimplementedFileSavingServer()
}

func RegisterFileSavingServer(s grpc.ServiceRegistrar, srv FileSavingServer) {
	// If the following call panics, it indicates UnimplementedFileSavingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileSaving_ServiceDesc, srv)
}

func _FileSaving_RequestNodeIPs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestNodeIPsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileSavingServer).RequestNodeIPs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileSaving_RequestNodeIPs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileSavingServer).RequestNodeIPs(ctx, req.(*RequestNodeIPsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FileSaving_ServiceDesc is the grpc.ServiceDesc for FileSaving service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileSaving_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "client.FileSaving",
	HandlerType: (*FileSavingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestNodeIPs",
			Handler:    _FileSaving_RequestNodeIPs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: ".proto/client/client.proto",
}
