// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: .proto/client/client.proto

package client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestNodeIPsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkNumber   int32                  `protobuf:"varint,1,opt,name=chunkNumber,proto3" json:"chunkNumber,omitempty"`
	ChunkSize     int32                  `protobuf:"varint,2,opt,name=chunkSize,proto3" json:"chunkSize,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=fileName,proto3" json:"fileName,omitempty"`
	UserName      string                 `protobuf:"bytes,4,opt,name=userName,proto3" json:"userName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestNodeIPsRequest) Reset() {
	*x = RequestNodeIPsRequest{}
	mi := &file___proto_client_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestNodeIPsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestNodeIPsRequest) ProtoMessage() {}

func (x *RequestNodeIPsRequest) ProtoReflect() protoreflect.Message {
	mi := &file___proto_client_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestNodeIPsRequest.ProtoReflect.Descriptor instead.
func (*RequestNodeIPsRequest) Descriptor() ([]byte, []int) {
	return file___proto_client_client_proto_rawDescGZIP(), []int{0}
}

func (x *RequestNodeIPsRequest) GetChunkNumber() int32 {
	if x != nil {
		return x.ChunkNumber
	}
	return 0
}

func (x *RequestNodeIPsRequest) GetChunkSize() int32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *RequestNodeIPsRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *RequestNodeIPsRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type ReplicaSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeIps       []string               `protobuf:"bytes,1,rep,name=node_ips,json=nodeIps,proto3" json:"node_ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaSet) Reset() {
	*x = ReplicaSet{}
	mi := &file___proto_client_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaSet) ProtoMessage() {}

func (x *ReplicaSet) ProtoReflect() protoreflect.Message {
	mi := &file___proto_client_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaSet.ProtoReflect.Descriptor instead.
func (*ReplicaSet) Descriptor() ([]byte, []int) {
	return file___proto_client_client_proto_rawDescGZIP(), []int{1}
}

func (x *ReplicaSet) GetNodeIps() []string {
	if x != nil {
		return x.NodeIps
	}
	return nil
}

type RequestNodeIPsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpAddress     []*ReplicaSet          `protobuf:"bytes,1,rep,name=ipAddress,proto3" json:"ipAddress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestNodeIPsResponse) Reset() {
	*x = RequestNodeIPsResponse{}
	mi := &file___proto_client_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestNodeIPsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestNodeIPsResponse) ProtoMessage() {}

func (x *RequestNodeIPsResponse) ProtoReflect() protoreflect.Message {
	mi := &file___proto_client_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestNodeIPsResponse.ProtoReflect.Descriptor instead.
func (*RequestNodeIPsResponse) Descriptor() ([]byte, []int) {
	return file___proto_client_client_proto_rawDescGZIP(), []int{2}
}

func (x *RequestNodeIPsResponse) GetIpAddress() []*ReplicaSet {
	if x != nil {
		return x.IpAddress
	}
	return nil
}

var File___proto_client_client_proto protoreflect.FileDescriptor

const file___proto_client_client_proto_rawDesc = "" +
	"\n" +
	"\x1a.proto/client/client.proto\x12\x06client\"\x8f\x01\n" +
	"\x15RequestNodeIPsRequest\x12 \n" +
	"\vchunkNumber\x18\x01 \x01(\x05R\vchunkNumber\x12\x1c\n" +
	"\tchunkSize\x18\x02 \x01(\x05R\tchunkSize\x12\x1a\n" +
	"\bfileName\x18\x03 \x01(\tR\bfileName\x12\x1a\n" +
	"\buserName\x18\x04 \x01(\tR\buserName\"'\n" +
	"\n" +
	"ReplicaSet\x12\x19\n" +
	"\bnode_ips\x18\x01 \x03(\tR\anodeIps\"J\n" +
	"\x16RequestNodeIPsResponse\x120\n" +
	"\tipAddress\x18\x01 \x03(\v2\x12.client.ReplicaSetR\tipAddress2]\n" +
	"\n" +
	"FileSaving\x12O\n" +
	"\x0eRequestNodeIPs\x12\x1d.client.RequestNodeIPsRequest\x1a\x1e.client.RequestNodeIPsResponseB(Z&distributedFileSystem/pkg/proto/clientb\x06proto3"

var (
	file___proto_client_client_proto_rawDescOnce sync.Once
	file___proto_client_client_proto_rawDescData []byte
)

func file___proto_client_client_proto_rawDescGZIP() []byte {
	file___proto_client_client_proto_rawDescOnce.Do(func() {
		file___proto_client_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file___proto_client_client_proto_rawDesc), len(file___proto_client_client_proto_rawDesc)))
	})
	return file___proto_client_client_proto_rawDescData
}

var file___proto_client_client_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file___proto_client_client_proto_goTypes = []any{
	(*RequestNodeIPsRequest)(nil),  // 0: client.RequestNodeIPsRequest
	(*ReplicaSet)(nil),             // 1: client.ReplicaSet
	(*RequestNodeIPsResponse)(nil), // 2: client.RequestNodeIPsResponse
}
var file___proto_client_client_proto_depIdxs = []int32{
	1, // 0: client.RequestNodeIPsResponse.ipAddress:type_name -> client.ReplicaSet
	0, // 1: client.FileSaving.RequestNodeIPs:input_type -> client.RequestNodeIPsRequest
	2, // 2: client.FileSaving.RequestNodeIPs:output_type -> client.RequestNodeIPsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file___proto_client_client_proto_init() }
func file___proto_client_client_proto_init() {
	if File___proto_client_client_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file___proto_client_client_proto_rawDesc), len(file___proto_client_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file___proto_client_client_proto_goTypes,
		DependencyIndexes: file___proto_client_client_proto_depIdxs,
		MessageInfos:      file___proto_client_client_proto_msgTypes,
	}.Build()
	File___proto_client_client_proto = out.File
	file___proto_client_client_proto_goTypes = nil
	file___proto_client_client_proto_depIdxs = nil
}
